<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>PizzaMaker</RootNamespace>
    <AssemblyName>PizzaMaker</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PizzaMakerClassLibrary\PizzaMakerClassLibrary.csproj" />
  </ItemGroup>
</Project>
